src/Entity/Classe.php
<?php

namespace App\Entity;

use App\Repository\ClasseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClasseRepository::class)]
class Classe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_classe = null;

    #[ORM\Column(length: 255)]
    private ?string $niveau = null;

    /**
     * @var Collection<int, Eleve>
     */
    #[ORM\OneToMany(targetEntity: Eleve::class, mappedBy: 'class')]
    private Collection $eleves;

    public function __construct()
    {
        $this->eleves = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomClasse(): ?string
    {
        return $this->nom_classe;
    }

    public function setNomClasse(string $nom_classe): static
    {
        $this->nom_classe = $nom_classe;

        return $this;
    }

    public function getNiveau(): ?string
    {
        return $this->niveau;
    }

    public function setNiveau(string $niveau): static
    {
        $this->niveau = $niveau;

        return $this;
    }

    /**
     * @return Collection<int, Eleve>
     */
    public function getEleves(): Collection
    {
        return $this->eleves;
    }

    public function addElefe(Eleve $elefe): static
    {
        if (!$this->eleves->contains($elefe)) {
            $this->eleves->add($elefe);
            $elefe->setClass($this);
        }

        return $this;
    }

    public function removeElefe(Eleve $elefe): static
    {
        if ($this->eleves->removeElement($elefe)) {
            // set the owning side to null (unless already changed)
            if ($elefe->getClass() === $this) {
                $elefe->setClass(null);
            }
        }

        return $this;
    }
}

src/Entity/Eleve.php
<?php

namespace App\Entity;

use App\Repository\EleveRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EleveRepository::class)]
class Eleve
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\ManyToOne(inversedBy: 'eleves')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Classe $class = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getClass(): ?Classe
    {
        return $this->class;
    }

    public function setClass(?Classe $class): static
    {
        $this->class = $class;

        return $this;
    }
}

src/Controller/ClasseController.php
<?php

namespace App\Controller;

use App\Entity\Classe;
use App\Repository\ClasseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class ClasseController extends AbstractController
{
    #[Route('/classe', name: 'app_classe', methods: ['GET'])]
    public function index(ClasseRepository $classeRepository): Response
    {
        $classes = $classeRepository->findAll();

        return $this->render('classe/index.html.twig', [
            'classes' => $classes
        ]);
    }
}

src/Controller/EleveController.php
<?php

namespace App\Controller;

use App\Repository\EleveRepository;
use App\Entity\Eleve;
use App\Form\EleveType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Entity\Classe;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

final class EleveController extends AbstractController
{
    #[Route('/eleve', name: 'app_eleve', methods: ['GET'])]
    public function index(EleveRepository $eleveRepository): Response
    {
        $eleves = $eleveRepository->findAll();
        return $this->render('eleve/index.html.twig', [
            'controller_name' => 'EleveController',
            'eleves' => $eleves

        ]);
    }

    #[Route('/eleve/ajouter', name: 'app_eleve_ajouter')]
    public function ajouter(Request $request, EntityManagerInterface $em): Response
{
    $eleve = new Eleve();

    $form = $this->createForm(EleveType::class, $eleve);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $em->persist($eleve);
        $em->flush();

        $this->addFlash('success', 'Élève ajouté avec succès');
        return $this->redirectToRoute('app_eleve_ajouter');
    }

    return $this->render('eleve/ajouter.html.twig', [
        'form' => $form->createView()
    ]);
}

#[Route('/eleve/update/{id}', name: 'eleve_update', methods: ['POST'])]
public function update(Request $request, EntityManagerInterface $entityManager, int $id): Response
{
    $eleve = $entityManager->getRepository(Eleve::class)->find($id);

    if (!$eleve) {
        throw $this->createNotFoundException('No eleve found for id '.$id);
    }
    
    $prenom = $request->request->get('prenom','');
    $eleve->setPrenom($prenom);

    $nom = $request->request->get('nom','');
    $eleve->setNom($nom);


    $entityManager->flush();

    return $this->redirectToRoute('app_eleve');
}

#[Route('/eleve/delete/{id}', name: 'eleve_delete', methods: ['POST'])]
public function delete(EntityManagerInterface $entityManager, int $id):Response{

    $eleve = $entityManager->getRepository(Eleve::class)->find($id);
    $entityManager->remove($eleve);
    $entityManager->flush();
    return $this->redirectToRoute('app_eleve');
}
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>

        <link rel="stylesheet" href="/css/app.css">

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/classe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des classes{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Liste des classes</h1>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nom de la classe</th>
                <th>Niveau</th>
            </tr>
        </thead>
        <tbody>
            {% for classe in classes %}
                <tr>
                    <td>{{ classe.id }}</td>
                    <td>{{ classe.nomClasse }}</td>
                    <td>{{ classe.niveau }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block javascripts %}
    <script type="module" src="{{ asset('assets/bootstrap.js') }}"></script>
{% endblock %}

templates/eleve/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un élève{% endblock %}

{% block body %}

<div class="example-wrapper add-form">

    <h1>Ajouter un élève</h1>
        <a href="{{ path('app_eleve') }}" class="btn-blue mb-20">← Retour à la liste</a>



    {% for message in app.flashes('success') %}
        <div class="flash-success">{{ message }}</div>
    {% endfor %}

    {{ form_start(form) }}
        {{ form_widget(form) }}
    

</div>

{% endblock %}

templates/eleve/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EleveController!{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1>Liste des élèves</h1>
           <a href="{{ path('app_eleve_ajouter') }}" class="btn-blue mb-20">Ajouter un élève</a>


    <table>
    
        <thead>
            <tr>
                <th>Classe</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
            {% for eleve in eleves %}
                <tr>
                    <td>{{ eleve.id }}</td>
                    <td>{{ eleve.prenom }}</td>
                    <td>{{ eleve.nom }}</td>

                    <td>
                        <div class="actions">

                            <!-- Update -->
                            <form action="{{ path('eleve_update', { id: eleve.id }) }}" method="post" class="action-left">
                                <input type="text" name="prenom" value="{{ eleve.prenom }}">
                                <input type="text" name="nom" value="{{ eleve.nom }}">
                                <button type="submit" class="modify">Modifier</button>
                            </form>
                            
                            <!-- Delete -->
                            <form action="{{ path('eleve_delete', { id: eleve.id }) }}" method="post" class="action-right">
                                <button type="submit" class="delete">Supprimer</button>
                            </form>

                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>

    </table>
</div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}